version: "2.4"

services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - config-analysis-ik:/usr/share/elasticsearch/config/analysis-ik
      - ./analysis-ik-8.11.3:/usr/share/elasticsearch/plugins/analysis-ik
    user: "0"
    command: >
      bash -c '

        echo "Preparing local analysis-ik plugin"

        chmod -R 755 /usr/share/elasticsearch/bin
        chmod -R 755 /usr/share/elasticsearch/jdk/bin/java
        chmod -R 755 /usr/share/elasticsearch/config

        if [ ! -f /usr/share/elasticsearch/plugins/analysis-ik/plugin-descriptor.properties ]; then
          echo "ERROR: analysis-ik plugin is not mounted correctly";
          echo "Expected: /usr/share/elasticsearch/plugins/analysis-ik/plugin-descriptor.properties";
          exit 1;
        fi

        rm -f /usr/share/elasticsearch/plugins/analysis-ik/.DS_STORE || true
        rm -f /usr/share/elasticsearch/.DS_STORE || true
        rm -f /usr/share/elasticsearch/config/.DS_STORE || true

        chmod -R 755 /usr/share/elasticsearch/plugins/analysis-ik

        echo "Installed plugins:"
        bin/elasticsearch-plugin list

        ls -la /usr/share/elasticsearch/plugins/analysis-ik || true
        echo "Setup complete";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -d /usr/share/elasticsearch/plugins/analysis-ik ] || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-single
    environment:
      - node.name=es-single
      - cluster.name=${CLUSTER_NAME}-single
      - discovery.type=single-node
#      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    mem_limit: ${MEM_LIMIT:-2147483648}
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
    depends_on:
      setup:
        condition: service_completed_successfully
    ports:
      - "${ES_PORT}:9200"
    volumes:
      - esdata_single:/usr/share/elasticsearch/data
      - ./analysis-ik-8.11.3:/usr/share/elasticsearch/plugins/analysis-ik
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10

  kibana:
     image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
     container_name: kibana-single
     depends_on:
       - elasticsearch
     environment:
       - SERVERNAME=kibana
       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
       - ELASTICSEARCH_USERNAME=kibana_system
       - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
       - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY:-aaaaaaaa-c4d3-4a0a-8290-2abcb83ab3aa}
     ports:
       - "${KIBANA_PORT}:5601"
     mem_limit: ${MEM_LIMIT:-2147483648}
     volumes:
       - kibanadata:/usr/share/kibana/data
     restart: unless-stopped
     healthcheck:
       test: ["CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 200' || exit 1"]
       interval: 10s
       timeout: 10s
       retries: 10

volumes:
  esdata_single:
    driver: local
  kibanadata:
    driver: local
  config-analysis-ik:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./analysis-ik-8.11.3/config"